# Generated by Django 4.0.4 on 2022-04-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'product_gallery', 'verbose_name_plural': 'Product Gallery'},
        ),
    ]
